name: Auto Increment Tag

on:
  push:
    branches: [ "**" ]

jobs:
  increment-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Faz o checkout do c√≥digo na branch atual

      - name: Get Last Tag and Increment
        run: |
          git status

          git tag

      - name: Push New Tag
        run: |
          echo "Nova tag criada e empurrada: $VERSION_TAG"