name: travel-order-app

# on:
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      - uses: actions/checkout@v4

      # - name: Copy .env
      #   working-directory: ./api-travel-orders
      #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # - name: Install Dependencies
      #   working-directory: ./api-travel-orders
      #   run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # - name: Generate key
      #   working-directory: ./api-travel-orders
      #   run: php artisan key:generate
        
      # - name: Directory Permissions
      #   working-directory: ./api-travel-orders
      #   run: chmod -R 777 storage bootstrap/cache

      # - name: Upload a Build Artifact para ser utilizado nos demais steps
      #   uses: actions/upload-artifact@v4.2.0
      #   with:
      #     name: api-travel-orders
      #     path: api-travel-orders

      - name: Get  the last tag on the commit
        id: get_tag
        run: |
          # Recupera a Ãºltima tag associada ao commit atual
          VERSION_APP=$(git describe --tags --abbrev=0)
          echo "${VERSION_APP}"
          echo "VERSION_APP=${VERSION_APP}" >> $GITHUB_ENV

      - name: CHECK VERSION_APP
        run: echo "github.ref_name ${{ env.VERSION_APP }}"
  # test-app:
  #   needs: build
  #   uses: ./.github/workflows/test-app.yml
  #   secrets: inherit

  # publish-docker-hub-app:
  #   needs: [build, test-app]
  #   uses: ./.github/workflows/publish-docker-hub-app.yml
  #   secrets: inherit